### ISSUE TITLE
Durum takibini gösteren badge için istek

### ISSUE THREAD

**Issue by hwpplayer1** [KolektifAPI/aktifRepo#1]
Merhaba, durum takibini gösteren badge kullanılabilir mi ?

Teşekkürler, iyi çalışmalar

**Comment by keyiflerolsun** [comment]
Mert Gör:
Buraya farklı içerikler konulabilir, ne kadar test edildi, heroku'ya mı deploy edildi, gibi ...

https://shields.io/
bunlar burda dursun :)
